---
title: "Final Project Write-Up"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> introduction 

Policymakers have recognized that children across the U.S. are being left behind, and that families and children of color experience disparate outcomes with their white counterparts. Detroit, with a long history of high unemployment, population decline, and urban decay, is not immune from this trend. In fact, the city and the state of Michigan have some of the most segregated schools and some of the highest rates of children living in poverty. A lot of work has been done to bring these issues to the forefront of the policy debate, and this project serves as a visual addition to this fight. Broadly, this project seeks to provide a picture of at-risk families living in the Detroit, and to provide a meaningful metric that is represented geospatially to help ensure the most vulnerable areas are included in the rebuilding of Detroit.   
	
> methods

The goal of the project was to create and visualize an index that represented the most at-risk children in the state of Michigan. Based on research, I chose to use race, income, population under the age of seventeen, and parental employment to build the index. These variables have been shown to contribute to the developmental outcomes for children and I used the `tidycensus` package to access the U.S. Census Bureau’s American Community Survey, ending in the year 2012. 

At first, each variable was standardized and represented geospatially using both `ggplot` and `leaflet`. However, feedback from the in-class presentation suggested that a standardized measure of each was not as insightful or accessible for the intended audience. In revision, each variable was re-calculated as a percent of within tract population. Representing each variable as a percent makes the visualization more interpretable. 
In the beginning stages of exploratory analysis, I found that simple density plots were relatively uninformative. But, households with similar demographics tend to cluster; therefore, a geospatial visualization is more informative. I started by looking at the demographics across the state at the county level, but this did not reflect the news stories I had read about poverty and unemployment in the state. The analysis was too broad to get a good sense of the underlying data. Instead, the analysis was re-focused on a single county, Wayne County, and at the census tract level. Wayne County was chosen because it includes the city of Detroit. 

More patterns started to emerge when the demographic variables were visualized at the census tract level. These thematic maps are meant to show each attribute, the spatial patterns of each attribute, and the relationships between these places. A conscious choice was made to keep each attribute continuous, instead of categorical. The fluidity of the color scale and the choice of palette helped to stress the areas with high rates of poverty, unemployment, and non-white families. Instead of a typical choropleth palette with a single color, the darker tones of purple help to show low percentages while the bright shades of orange and yellow help the areas with high percentages stick out. The same palette is used for each of the single variable thematic maps, while a different palette is used for index variable map. This shift in the color palette is meant to highlight the shift in analysis – from exploratory to spatial analysis. 

Of course, the single map representing the index was the final goal of the project, but, on its own, the map seems out of context and uninterpretable. Using a `flexdashboard` layout, the audience is, first, introduced to the problem, and, then, the story is slowly revealed through a storyboard that includes the single attribute maps with explanations. This breaks up the large amount of data being presented in the final visualization, and it allows the audience to gain context with each new slide that builds to the insight provided by the final visualization. 

> results   

From this work, the audience has learned the spatial patterns of race, poverty, and unemployment in and around the city of Detroit.  And, that more needs to be done using both a two-generation approach – helping parents while helping their children – and a racial equity lens. The visualization is truthful because (1) it comes directly from a publicly available dataset that has (2) undergone minimal transformation from collection to dispersion. The visualization is most functional as a map. The purpose is to see the underlying patterns of race, income, and unemployment, and how these are spatially correlated with (or not) the areas still in decay in the city of Detroit. Most of the only positive feedback from the presentation was that the thematic maps were pretty. The aesthetic of the whole dashboard was meant to be simple, straightforward, and accessible. The intended audience is a policymaker. Therefore, insight is built as the user moves through the storyboard. The context provided by the initial maps and explanations allows for an ‘a-ha’ moment with the final visualization. Together, the project tells a story that is not unique to Detroit or Michigan, but a story that is true across the U.S. The information is relevant and the topic, child well-being, is important, especially through a racial equity lens. 




